from dataclasses import dataclass
from typing import Literal

from pdi.core.config import Settings

Classification = Literal["A", "B", "C", "D"]
InputKind = Literal["boolean", "integer", "number", "text", "select", "resource_limits"]


@dataclass(frozen=True, slots=True)
class SettingDefinition:
    key: str
    domain: str
    classification: Classification
    label: str
    description: str
    editable: bool = False
    requires_restart: bool = False
    input_kind: InputKind = "text"
    minimum: float | None = None
    maximum: float | None = None
    options: tuple[str, ...] = ()


def setting(
    key: str,
    domain: str,
    classification: Classification,
    label: str,
    description: str,
    **values: object,
) -> SettingDefinition:
    return SettingDefinition(
        key=key,
        domain=domain,
        classification=classification,
        label=label,
        description=description,
        **values,  # type: ignore[arg-type]
    )


EDITABLE = {
    item.key: item
    for item in (
        setting(
            "log_level",
            "general",
            "B",
            "Log level",
            "Service logging detail after restart.",
            editable=True,
            requires_restart=True,
            input_kind="select",
            options=("INFO", "WARNING", "ERROR"),
        ),
        setting(
            "max_upload_size",
            "documents",
            "B",
            "Maximum document size",
            "Maximum accepted upload or source document size in bytes.",
            editable=True,
            input_kind="integer",
            minimum=1_048_576,
            maximum=1_073_741_824,
        ),
        setting(
            "ocr_enabled",
            "ocr",
            "B",
            "OCR policy",
            "Run OCR automatically when embedded text is insufficient.",
            editable=True,
            input_kind="boolean",
        ),
        setting(
            "ocr_language",
            "ocr",
            "B",
            "OCR languages",
            "Installed Tesseract language codes joined with +.",
            editable=True,
        ),
        setting(
            "ocr_minimum_characters_per_page",
            "ocr",
            "B",
            "Text quality threshold",
            "Minimum non-whitespace characters expected on each page before OCR is considered.",
            editable=True,
            input_kind="integer",
            minimum=10,
            maximum=500,
        ),
        setting(
            "ocr_command_timeout",
            "ocr",
            "B",
            "OCR timeout",
            "Maximum OCR runtime in seconds.",
            editable=True,
            input_kind="integer",
            minimum=10,
            maximum=3600,
        ),
        setting(
            "ocr_max_pages",
            "ocr",
            "B",
            "OCR page limit",
            "Maximum pages accepted by one OCR task.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=1000,
        ),
        setting(
            "ocr_max_image_mpixels",
            "ocr",
            "B",
            "Image pixel limit",
            "Maximum megapixels accepted for OCR.",
            editable=True,
            input_kind="number",
            minimum=1,
            maximum=1000,
        ),
        setting(
            "ocr_force_rotation",
            "ocr",
            "B",
            "Automatic orientation",
            "Allow OCRmyPDF to correct page orientation.",
            editable=True,
            input_kind="boolean",
        ),
        setting(
            "intelligence_provider",
            "intelligence",
            "B",
            "Provider",
            "Select deterministic processing or a deployment-configured local Ollama service.",
            editable=True,
            input_kind="select",
            options=("deterministic", "ollama"),
        ),
        setting(
            "ollama_model",
            "intelligence",
            "B",
            "Local model",
            "Select a model from the deployment allow-list.",
            editable=True,
            input_kind="select",
        ),
        setting(
            "intelligence_timeout_seconds",
            "intelligence",
            "B",
            "Intelligence timeout",
            "Maximum provider request duration in seconds.",
            editable=True,
            input_kind="number",
            minimum=1,
            maximum=600,
        ),
        setting(
            "intelligence_max_input_characters",
            "intelligence",
            "B",
            "Input character limit",
            "Maximum canonical text sent to the intelligence provider.",
            editable=True,
            input_kind="integer",
            minimum=1000,
            maximum=2_000_000,
        ),
        setting(
            "consume_stability_seconds",
            "ingestion",
            "B",
            "Scanner stability window",
            "Seconds a scanner file must remain unchanged before it is claimed.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=3600,
        ),
        setting(
            "consume_poll_interval",
            "ingestion",
            "B",
            "Scanner poll interval",
            "Seconds between consume-folder checks.",
            editable=True,
            input_kind="number",
            minimum=0.2,
            maximum=300,
        ),
        setting(
            "mail_poll_interval",
            "ingestion",
            "B",
            "Mailbox poll interval",
            "Seconds between read-only mailbox checks.",
            editable=True,
            input_kind="number",
            minimum=5,
            maximum=3600,
        ),
        setting(
            "imap_max_messages_per_poll",
            "ingestion",
            "B",
            "Mailbox batch limit",
            "Maximum messages inspected during one poll.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=1000,
        ),
        setting(
            "imap_socket_timeout_seconds",
            "ingestion",
            "B",
            "Mailbox timeout",
            "Maximum IMAP socket wait in seconds.",
            editable=True,
            input_kind="number",
            minimum=1,
            maximum=120,
        ),
        setting(
            "worker_poll_interval",
            "execution",
            "B",
            "Queue poll interval",
            "Seconds between empty queue polls.",
            editable=True,
            input_kind="number",
            minimum=0.1,
            maximum=300,
        ),
        setting(
            "worker_max_attempts",
            "execution",
            "B",
            "Maximum attempts",
            "Bounded attempts for newly queued work.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=20,
        ),
        setting(
            "worker_job_timeout",
            "execution",
            "B",
            "Stale job timeout",
            "Seconds before an abandoned claim can be recovered.",
            editable=True,
            input_kind="integer",
            minimum=10,
            maximum=86400,
        ),
        setting(
            "worker_concurrency",
            "execution",
            "B",
            "Worker concurrency",
            "Parallel worker slots created when the worker starts.",
            editable=True,
            requires_restart=True,
            input_kind="integer",
            minimum=1,
            maximum=4,
        ),
        setting(
            "execution_resource_limits",
            "execution",
            "B",
            "Resource limits",
            "Per-resource admission limits; zero and unbounded values are rejected.",
            editable=True,
            input_kind="resource_limits",
        ),
        setting(
            "execution_starvation_seconds",
            "execution",
            "B",
            "Starvation threshold",
            "Age after which lower-priority work receives bounded preference.",
            editable=True,
            input_kind="integer",
            minimum=30,
            maximum=86400,
        ),
        setting(
            "execution_heartbeat_seconds",
            "execution",
            "B",
            "Heartbeat interval",
            "Seconds between durable claim heartbeats.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=60,
        ),
        setting(
            "update_channel",
            "updates",
            "B",
            "Update checks",
            "Disable checks, check manually, or use a weekly notification cadence.",
            editable=True,
            input_kind="select",
            options=("disabled", "manual", "weekly"),
        ),
        setting(
            "backup_schedule_enabled",
            "backup",
            "B",
            "Scheduled backups",
            "Create coordinated backups on the configured interval.",
            editable=True,
            input_kind="boolean",
        ),
        setting(
            "backup_interval_hours",
            "backup",
            "B",
            "Backup interval",
            "Hours between scheduled coordinated backups.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=168,
        ),
        setting(
            "backup_retention_count",
            "backup",
            "B",
            "Scheduled backup retention",
            "Number of verified scheduled backups retained locally.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=365,
        ),
        setting(
            "reminders_enabled",
            "notifications",
            "B",
            "In-app reminders",
            "Generate private in-app deadline reminders. No email is sent.",
            editable=True,
            input_kind="boolean",
        ),
        *(
            setting(
                f"deadline_lead_days_{deadline_type}",
                "notifications",
                "B",
                f"{label} lead time",
                f"Days before a reviewed {label.lower()} deadline to create one reminder.",
                editable=True,
                input_kind="integer",
                minimum=0,
                maximum=365,
            )
            for deadline_type, label in (
                ("payment", "Payment"),
                ("cancellation", "Cancellation"),
                ("renewal", "Renewal"),
                ("response", "Response"),
                ("submission", "Submission"),
                ("appointment", "Appointment"),
                ("other", "Other"),
            )
        ),
        setting(
            "update_allow_prerelease",
            "updates",
            "B",
            "Include prereleases",
            "Allow release discovery to include prereleases. Disabled by default.",
            editable=True,
            input_kind="boolean",
        ),
        setting(
            "update_check_timeout_seconds",
            "updates",
            "B",
            "Update check timeout",
            "Maximum release metadata request duration.",
            editable=True,
            input_kind="number",
            minimum=1,
            maximum=30,
        ),
        setting(
            "update_metadata_cache_seconds",
            "updates",
            "B",
            "Update metadata cache",
            "Seconds before cached release metadata expires.",
            editable=True,
            input_kind="integer",
            minimum=60,
            maximum=86400,
        ),
        setting(
            "update_min_free_bytes",
            "updates",
            "B",
            "Required free storage",
            "Minimum free bytes required by update preflight.",
            editable=True,
            input_kind="integer",
            minimum=0,
            maximum=10_995_116_277_760,
        ),
        setting(
            "update_drain_timeout_seconds",
            "updates",
            "B",
            "Drain timeout",
            "Maximum seconds to wait for active work before installation.",
            editable=True,
            input_kind="integer",
            minimum=0,
            maximum=3600,
        ),
        setting(
            "session_ttl_seconds",
            "security",
            "B",
            "Session lifetime",
            "Lifetime of newly issued browser sessions in seconds.",
            editable=True,
            input_kind="integer",
            minimum=300,
            maximum=2592000,
        ),
        setting(
            "login_max_attempts",
            "security",
            "B",
            "Login attempt limit",
            "Maximum attempts within the login window.",
            editable=True,
            input_kind="integer",
            minimum=1,
            maximum=50,
        ),
        setting(
            "login_window_seconds",
            "security",
            "B",
            "Login attempt window",
            "Rate-limit observation window in seconds.",
            editable=True,
            input_kind="integer",
            minimum=60,
            maximum=86400,
        ),
    )
}


# Every environment-backed value has an explicit owner. This table is intentionally
# exhaustive; a regression test requires new Settings fields to be classified.
CLASSIFICATIONS: dict[str, Classification] = {
    "env": "C",
    "database_url": "D",
    "storage_path": "C",
    "max_upload_size": "B",
    "log_level": "B",
    "cors_origins": "C",
    "worker_poll_interval": "B",
    "worker_max_attempts": "B",
    "worker_job_timeout": "B",
    "worker_concurrency": "B",
    "worker_identity": "C",
    "execution_resource_limits": "B",
    "execution_starvation_seconds": "B",
    "execution_heartbeat_seconds": "B",
    "ocr_enabled": "B",
    "ocr_provider": "C",
    "ocr_command_timeout": "B",
    "ocr_language": "B",
    "ocr_minimum_characters_per_page": "B",
    "ocr_max_pages": "B",
    "ocr_max_image_mpixels": "B",
    "ocr_force_rotation": "B",
    "ocr_max_derived_size": "C",
    "intelligence_provider": "B",
    "intelligence_timeout_seconds": "B",
    "intelligence_max_input_characters": "B",
    "ollama_base_url": "C",
    "ollama_model": "B",
    "ollama_allowed_models": "C",
    "auth_enabled": "C",
    "setup_enabled": "C",
    "session_ttl_seconds": "B",
    "auth_secure_cookies": "C",
    "login_max_attempts": "B",
    "login_window_seconds": "B",
    "totp_encryption_key": "D",
    "build_revision": "C",
    "build_time": "C",
    "deployment_type": "C",
    "consume_path": "C",
    "consume_processing_path": "C",
    "consume_processed_path": "C",
    "consume_failed_path": "C",
    "consume_stability_seconds": "B",
    "consume_poll_interval": "B",
    "consume_enabled": "C",
    "mail_enabled": "C",
    "imap_host": "C",
    "imap_port": "C",
    "imap_user": "D",
    "imap_password_file": "D",
    "imap_mailbox": "C",
    "mail_poll_interval": "B",
    "imap_max_messages_per_poll": "B",
    "imap_socket_timeout_seconds": "B",
    "paperless_url": "C",
    "paperless_token_file": "D",
    "paperless_verify_tls": "C",
    "backup_path": "C",
    "backup_schedule_enabled": "B",
    "backup_interval_hours": "B",
    "backup_retention_count": "B",
    "backup_schedule_poll_seconds": "C",
    "reminders_enabled": "B",
    "reminder_poll_seconds": "C",
    "deadline_lead_days_payment": "B",
    "deadline_lead_days_cancellation": "B",
    "deadline_lead_days_renewal": "B",
    "deadline_lead_days_response": "B",
    "deadline_lead_days_submission": "B",
    "deadline_lead_days_appointment": "B",
    "deadline_lead_days_other": "B",
    "update_channel": "B",
    "update_allow_prerelease": "B",
    "update_github_api_url": "C",
    "update_manifest_name": "C",
    "update_check_timeout_seconds": "B",
    "update_metadata_cache_seconds": "B",
    "update_min_free_bytes": "B",
    "update_drain_timeout_seconds": "B",
    "update_backend_digest": "C",
    "update_web_digest": "C",
    "update_expected_schema": "C",
    "update_deployment_type": "C",
}

DOMAINS = (
    "general",
    "documents",
    "ocr",
    "intelligence",
    "ingestion",
    "search",
    "execution",
    "backup",
    "updates",
    "notifications",
    "security",
    "system",
)


def validate_catalog() -> None:
    fields = set(Settings.model_fields)
    classified = set(CLASSIFICATIONS)
    if fields != classified:
        missing = sorted(fields - classified)
        stale = sorted(classified - fields)
        raise RuntimeError(f"Settings classification mismatch; missing={missing}, stale={stale}")
    if set(EDITABLE) - fields:
        raise RuntimeError("Editable catalog contains unknown settings")
    if any(CLASSIFICATIONS[key] not in {"A", "B"} for key in EDITABLE):
        raise RuntimeError("Only A/B settings may be editable")
