"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, Check, Copy, Download, KeyRound, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  securityRequest, type SessionItem, type SystemInfo, type TokenItem, type TwoFactorStatus, type UserItem,
} from "@/lib/api/security";

function Message({ error, success }: { error?: string; success?: string }) {
  if (!error && !success) return null;
  return <p role={error ? "alert" : "status"} className={`mt-3 text-sm ${error ? "text-red-700" : "text-emerald-800"}`}>{error || success}</p>;
}

function Field({ label, name, type = "text", required = true, inputMode }: { label: string; name: string; type?: string; required?: boolean; inputMode?: React.HTMLAttributes<HTMLInputElement>["inputMode"] }) {
  return <label className="block text-xs font-medium text-stone-600">{label}<input className="field mt-1.5" name={name} type={type} required={required} inputMode={inputMode} /></label>;
}

export function AccountPanel() {
  const [message, setMessage] = useState({ error: "", success: "" });
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setMessage({ error: "", success: "" });
    const form = event.currentTarget; const data = new FormData(form);
    try {
      await securityRequest("/api/v1/account/password", { method: "POST", body: JSON.stringify({ current_password: data.get("current"), new_password: data.get("password"), new_password_confirmation: data.get("confirmation") }) });
      form.reset(); setMessage({ error: "", success: "Password changed. All previous sessions were revoked." });
    } catch (error) { setMessage({ error: (error as Error).message, success: "" }); }
  }
  return <SettingsPage title="Account" description="Change the password used to sign in to PDI."><form onSubmit={submit} className="panel max-w-xl space-y-4 p-5"><Field label="Current password" name="current" type="password" /><Field label="New password" name="password" type="password" /><Field label="Confirm new password" name="confirmation" type="password" /><Message {...message} /><Button type="submit">Change password</Button></form></SettingsPage>;
}

type Setup = { secret: string; provisioning_uri: string; qr_svg_base64: string; expires_at: string };
export function SecurityPanel() {
  const [status, setStatus] = useState<TwoFactorStatus | null>(null); const [setup, setSetup] = useState<Setup | null>(null);
  const [codes, setCodes] = useState<string[]>([]); const [message, setMessage] = useState({ error: "", success: "" });
  const load = useCallback(() => securityRequest<TwoFactorStatus>("/api/v1/account/2fa").then(setStatus).catch((error) => setMessage({ error: error.message, success: "" })), []);
  useEffect(() => { void load(); }, [load]);
  async function start(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { setSetup(await securityRequest<Setup>("/api/v1/account/2fa/setup", { method: "POST", body: JSON.stringify({ current_password: data.get("password") }) })); setMessage({ error: "", success: "Scan the QR code, then verify a code to activate 2FA." }); } catch (error) { setMessage({ error: (error as Error).message, success: "" }); } }
  async function factorAction(event: FormEvent<HTMLFormElement>, action: "enable" | "disable" | "recovery-codes") { event.preventDefault(); if (action === "disable" && !window.confirm("Disable two-factor authentication for this account?")) return; if (action === "recovery-codes" && !window.confirm("Invalidate all previous unused recovery codes?")) return; const data = new FormData(event.currentTarget); try { const result = await securityRequest<{ recovery_codes?: string[] }>(`/api/v1/account/2fa/${action}`, { method: "POST", body: JSON.stringify({ current_password: data.get("password"), code: data.get("code") }) }); if (result?.recovery_codes) setCodes(result.recovery_codes); if (action === "disable") { setSetup(null); setCodes([]); } await load(); setMessage({ error: "", success: action === "enable" ? "Two-factor authentication enabled." : action === "disable" ? "Two-factor authentication disabled." : "Recovery codes regenerated." }); } catch (error) { setMessage({ error: (error as Error).message, success: "" }); } }
  function downloadCodes() { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([codes.join("\n") + "\n"], { type: "text/plain" })); link.download = "pdi-recovery-codes.txt"; link.click(); URL.revokeObjectURL(link.href); }
  return <SettingsPage title="Security" description="Protect your account with a standards-compatible authenticator app.">
    <div className="panel max-w-2xl p-5"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-emerald-800" /><div><p className="font-medium text-stone-900">Two-factor authentication</p><p className="text-sm text-stone-500">{status?.enabled ? `Enabled · ${status.recovery_codes_remaining} recovery codes remain` : "Not enabled"}</p></div></div>
      {status && !status.encryption_configured ? <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">An administrator must configure the TOTP encryption key before setup.</p> : null}
      {!status?.enabled && !setup ? <form onSubmit={start} className="mt-5 grid max-w-sm gap-4"><Field label="Current password" name="password" type="password" /><Button disabled={!status?.encryption_configured}>Start setup</Button></form> : null}
      {setup && !status?.enabled ? <div className="mt-5 rounded-xl border border-stone-200 p-4"><p className="text-sm font-medium">1. Scan this QR code</p><img className="mt-3 size-48 rounded-lg bg-white p-2" alt="PDI authenticator setup QR code" src={`data:image/svg+xml;base64,${setup.qr_svg_base64}`} /><p className="mt-3 text-xs text-stone-500">Manual secret (shown only during setup)</p><code className="mt-1 block break-all rounded bg-stone-100 p-2 text-xs">{setup.secret}</code><p className="mt-5 text-sm font-medium">2. Verify and activate</p><form onSubmit={(event) => factorAction(event, "enable")} className="mt-3 grid max-w-sm gap-3"><Field label="Current password" name="password" type="password" /><Field label="6-digit authenticator code" name="code" inputMode="numeric" /><Button>Enable 2FA</Button></form></div> : null}
      {status?.enabled ? <div className="mt-5 grid gap-5 sm:grid-cols-2"><form onSubmit={(event) => factorAction(event, "recovery-codes")} className="rounded-xl border border-stone-200 p-4"><p className="text-sm font-medium">Regenerate recovery codes</p><p className="mb-3 text-xs text-stone-500">This invalidates all previous unused codes.</p><div className="space-y-3"><Field label="Current password" name="password" type="password" /><Field label="Authenticator code" name="code" /><Button variant="secondary">Regenerate</Button></div></form><form onSubmit={(event) => factorAction(event, "disable")} className="rounded-xl border border-red-200 p-4"><p className="text-sm font-medium text-red-800">Disable 2FA</p><p className="mb-3 text-xs text-stone-500">Password and authenticator verification are required.</p><div className="space-y-3"><Field label="Current password" name="password" type="password" /><Field label="Authenticator code" name="code" /><Button className="bg-red-700 hover:bg-red-600">Disable 2FA</Button></div></form></div> : null}
      {codes.length ? <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-medium text-amber-950">Save these recovery codes now</p><p className="text-sm text-amber-800">They will not be shown again. Each code works once.</p><div className="mt-3 grid grid-cols-2 gap-2 font-mono text-sm">{codes.map((code) => <code key={code}>{code}</code>)}</div><div className="mt-4 flex gap-2"><Button type="button" variant="secondary" onClick={() => navigator.clipboard.writeText(codes.join("\n"))}><Copy className="size-4" />Copy</Button><Button type="button" variant="secondary" onClick={downloadCodes}><Download className="size-4" />Download</Button></div></div> : null}<Message {...message} />
    </div></SettingsPage>;
}

export function SessionsPanel() {
  const [items, setItems] = useState<SessionItem[]>([]); const [message, setMessage] = useState({ error: "", success: "" });
  const load = useCallback(() => securityRequest<SessionItem[]>("/api/v1/account/sessions").then(setItems).catch((error) => setMessage({ error: error.message, success: "" })), []); useEffect(() => { void load(); }, [load]);
  async function revoke(path: string) { if (!window.confirm("Revoke the selected session access?")) return; try { await securityRequest(path, { method: "POST" }); await load(); setMessage({ error: "", success: "Session access revoked immediately." }); } catch (error) { setMessage({ error: (error as Error).message, success: "" }); } }
  return <SettingsPage title="Sessions" description="Review and revoke active browser sessions."><div className="panel max-w-3xl divide-y divide-stone-100">{items.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.current ? "Current session" : "Browser session"} {item.current ? <span className="status-pill border-emerald-200 bg-emerald-50 text-emerald-800">Current</span> : null}</p><p className="mt-1 text-xs text-stone-500">Created {new Date(item.created_at).toLocaleString()} · Last seen {new Date(item.last_seen_at).toLocaleString()}</p></div>{!item.current ? <Button variant="secondary" onClick={() => revoke(`/api/v1/account/sessions/${item.id}/revoke`)}>Revoke</Button> : null}</div>)}{!items.length ? <p className="p-5 text-sm text-stone-500">No active sessions found.</p> : null}</div><div className="mt-4"><Button variant="secondary" onClick={() => revoke("/api/v1/account/sessions/revoke-others")}>Revoke all other sessions</Button></div><Message {...message} /></SettingsPage>;
}

const scopes = ["documents:read", "search:read", "knowledge:read", "documents:ingest"];
export function TokensPanel() {
  const [items, setItems] = useState<TokenItem[]>([]); const [plaintext, setPlaintext] = useState(""); const [message, setMessage] = useState({ error: "", success: "" });
  const load = useCallback(() => securityRequest<TokenItem[]>("/api/v1/account/tokens").then(setItems).catch((error) => setMessage({ error: error.message, success: "" })), []); useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { const token = await securityRequest<TokenItem>("/api/v1/account/tokens", { method: "POST", body: JSON.stringify({ name: data.get("name"), scopes: data.getAll("scopes") }) }); setPlaintext(token.token ?? ""); form.reset(); await load(); setMessage({ error: "", success: "Token created." }); } catch (error) { setMessage({ error: (error as Error).message, success: "" }); } }
  async function revoke(id: string) { if (!window.confirm("Revoke this API token?")) return; try { await securityRequest(`/api/v1/account/tokens/${id}/revoke`, { method: "POST" }); await load(); } catch (error) { setMessage({ error: (error as Error).message, success: "" }); } }
  return <SettingsPage title="API Tokens" description="Create scoped credentials for trusted integrations."><form onSubmit={create} className="panel max-w-2xl p-5"><Field label="Token name" name="name" /><fieldset className="mt-4"><legend className="text-xs font-medium text-stone-600">Scopes</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{scopes.map((scope) => <label key={scope} className="flex items-center gap-2 text-sm"><input type="checkbox" name="scopes" value={scope} />{scope}</label>)}</div></fieldset><Button className="mt-5"><KeyRound className="size-4" />Create token</Button></form>{plaintext ? <div className="mt-4 max-w-2xl rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-medium">Copy this token now</p><p className="text-sm text-amber-800">The plaintext will never be shown again.</p><code className="mt-3 block break-all rounded bg-white p-3 text-xs">{plaintext}</code><Button className="mt-3" variant="secondary" onClick={() => navigator.clipboard.writeText(plaintext)}><Copy className="size-4" />Copy</Button></div> : null}<div className="panel mt-5 max-w-3xl divide-y divide-stone-100">{items.map((item) => <div key={item.id} className="flex items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.name} <code className="text-xs text-stone-500">{item.prefix}…</code></p><p className="text-xs text-stone-500">{item.scopes.join(" · ")} · Created {new Date(item.created_at).toLocaleDateString()}</p></div><span className={`status-pill ${item.revoked ? "border-stone-200 text-stone-500" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{item.revoked ? "Revoked" : "Active"}</span>{!item.revoked ? <Button variant="secondary" onClick={() => revoke(item.id)}>Revoke</Button> : null}</div>)}</div><Message {...message} /></SettingsPage>;
}

export function AboutPanel() {
  const [info, setInfo] = useState<SystemInfo | null>(null); const [error, setError] = useState(""); useEffect(() => { securityRequest<SystemInfo>("/api/v1/system/info").then(setInfo).catch((value) => setError(value.message)); }, []);
  if (!info) return <SettingsPage title="About" description="Version and runtime information."><div className="panel p-5 text-sm text-stone-500">{error || "Loading system information…"}</div></SettingsPage>;
  const groups = [{ title: "PDI", values: [["Product", info.product_version], ["Backend", info.backend.version], ["Backend revision", info.backend.revision], ["Backend built", info.backend.build_time], ["Web", info.web.version], ["Web revision", info.web.revision], ["Web built", info.web.build_time], ["Update channel", info.update.channel], ["Available update", info.update.available_version]] }, { title: "Database & runtime", values: [["Alembic", info.database.alembic_revision], ["Platform", info.runtime.platform], ["Architecture", info.runtime.architecture], ["Deployment", info.runtime.deployment_type]] }, { title: "OCR & intelligence", values: [["OCR provider", info.ocr.provider], ["OCRmyPDF", info.ocr.ocrmypdf_version], ["Tesseract", info.ocr.tesseract_version], ["Intelligence", info.intelligence.provider], ["Local model", info.intelligence.model]] }];
  return <SettingsPage title="About" description="Operator-safe build, database, and provider information.">{!info.version_consistent || info.warnings.length ? <div role="alert" className="mb-4 flex max-w-3xl gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mt-0.5 size-4 shrink-0" /><div>{info.warnings.map((warning) => <p key={warning}>{warning}</p>)}</div></div> : <div className="mb-4 flex max-w-3xl items-center gap-2 text-sm text-emerald-800"><Check className="size-4" />Backend and web versions are consistent.</div>}<div className="grid max-w-4xl gap-4 lg:grid-cols-3">{groups.map((group) => <section key={group.title} className="panel p-5"><h2 className="font-medium">{group.title}</h2><dl className="mt-4 space-y-3">{group.values.map(([label, value]) => <div key={label}><dt className="text-xs text-stone-500">{label}</dt><dd className="mt-0.5 break-all text-sm">{value || "Unavailable"}</dd></div>)}</dl></section>)}</div></SettingsPage>;
}

export function UsersAdminPanel() {
  const [items, setItems] = useState<UserItem[]>([]); const [message, setMessage] = useState({ error: "", success: "" });
  const load = useCallback(() => securityRequest<UserItem[]>("/api/v1/admin/users").then(setItems).catch((error) => setMessage({ error: error.message, success: "" })), []); useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await securityRequest("/api/v1/admin/users", { method: "POST", body: JSON.stringify({ username: data.get("username"), password: data.get("password"), role: data.get("role") }) }); form.reset(); await load(); setMessage({ error: "", success: "User created." }); } catch (error) { setMessage({ error: (error as Error).message, success: "" }); } }
  async function mutate(path: string, body?: object, confirmation?: string) { if (confirmation && !window.confirm(confirmation)) return; try { await securityRequest(path, { method: "POST", body: body ? JSON.stringify(body) : undefined }); await load(); setMessage({ error: "", success: "User access updated." }); } catch (error) { setMessage({ error: (error as Error).message, success: "" }); } }
  return <SettingsPage title="Users" description="Minimal administration for this private PDI installation."><form onSubmit={create} className="panel grid max-w-3xl gap-4 p-5 sm:grid-cols-3"><Field label="Username" name="username" /><Field label="Initial password" name="password" type="password" /><label className="text-xs font-medium text-stone-600">Role<select name="role" className="field mt-1.5"><option value="user">User</option><option value="read_only">Read-only</option><option value="admin">Admin</option></select></label><Button className="sm:col-span-3 sm:w-fit">Create user</Button></form><div className="panel mt-5 max-w-4xl divide-y divide-stone-100">{items.map((user) => <div key={user.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-44 flex-1"><p className="text-sm font-medium">{user.username}</p><p className="text-xs text-stone-500">{user.two_factor_enabled ? "2FA enabled" : "2FA not enabled"} · {user.is_active ? "Active" : "Inactive"}</p></div><select aria-label={`Role for ${user.username}`} className="field w-36" value={user.role} onChange={(event) => mutate(`/api/v1/admin/users/${user.id}/role`, { role: event.target.value }, `Change ${user.username}'s role?`)}><option value="admin">Admin</option><option value="user">User</option><option value="read_only">Read-only</option></select><Button variant="secondary" onClick={() => mutate(`/api/v1/admin/users/${user.id}/active`, { is_active: !user.is_active }, user.is_active ? `Deactivate ${user.username} and revoke active access?` : undefined)}>{user.is_active ? "Deactivate" : "Reactivate"}</Button><Button variant="secondary" onClick={() => mutate(`/api/v1/admin/users/${user.id}/revoke-access`, undefined, "Revoke all sessions and tokens for this user?")}>Revoke access</Button></div>)}</div><Message {...message} /></SettingsPage>;
}

function SettingsPage({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="page"><p className="eyebrow">Settings</p><h1 className="page-title mt-1">{title}</h1><p className="page-description">{description}</p><div className="mt-6">{children}</div></div>; }
