import Link from "next/link";
import { KnowledgeShell, dateLabel, label } from "@/components/knowledge-shell";
import { getKnowledgeReview, getTimeline } from "@/lib/api/server";

interface Filters { life_area?: string; event_type?: string; date_from?: string; date_to?: string }
export const metadata = { title: "Timeline" };
export default async function TimelinePage({ searchParams }: { searchParams: Promise<Filters> }) {
  const filters = await searchParams; const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value); });
  const [data, pending] = await Promise.all([getTimeline(params), getKnowledgeReview("event")]);
  const eventTypes = ["document_received","contract_started","contract_changed","contract_renewed","contract_cancelled","contract_ended","payment_due","invoice_issued","policy_changed","tariff_changed","deadline_set","official_decision","other"];
  return <KnowledgeShell eyebrow="Life model" title="Timeline" description="Confirmed, document-backed events in chronological order—not document upload history or generated interpretation."><form className="mb-6 grid gap-2 rounded-xl bg-stone-100/70 p-3 sm:grid-cols-4"><select name="life_area" aria-label="Life area" defaultValue={filters.life_area ?? ""} className="field"><option value="">All life areas</option>{["insurance","finance","vehicle","home","health","tax","work","travel","personal","other"].map((area) => <option key={area} value={area}>{label(area)}</option>)}</select><select name="event_type" aria-label="Event type" defaultValue={filters.event_type ?? ""} className="field"><option value="">All event types</option>{eventTypes.map((type) => <option key={type} value={type}>{label(type)}</option>)}</select><label className="text-[11px] text-stone-500"><span className="mb-1 block">From date</span><input name="date_from" type="date" defaultValue={filters.date_from ?? ""} className="field" /></label><button className="self-end rounded-lg bg-stone-900 px-3 py-2 text-sm text-white">Apply filters</button></form>{data.items.length ? <ol className="divide-y divide-stone-200 border-y border-stone-200">{data.items.map((item) => <li key={item.id} className="grid gap-3 py-5 sm:grid-cols-[130px_1fr]"><time className="text-xs font-medium text-stone-400">{dateLabel(item.event_date)}</time><div className="min-w-0"><h2 className="break-words text-sm font-medium text-stone-900">{item.title}</h2><p className="mt-1 text-xs text-stone-400">{label(item.life_area)} · {label(item.event_type)} · {label(item.event_date_precision)}</p>{item.evidence[0] ? <blockquote className="mt-3 border-l-2 border-amber-200 pl-3 text-sm text-stone-600">“{item.evidence[0].text}” <span className="text-xs text-stone-400">Page {item.evidence[0].page}</span></blockquote> : null}<Link href={`/documents/${item.source_document_id}`} className="mt-2 inline-block text-xs text-stone-500 hover:text-stone-950">Open source document →</Link></div></li>)}</ol> : <div className="py-16 text-center"><p className="text-sm text-stone-500">No confirmed document-backed events match these filters.</p>{pending.total ? <Link href="/review/knowledge" className="mt-3 inline-block text-sm font-medium text-stone-700 underline underline-offset-4">Review event suggestions ({pending.total})</Link> : null}</div>}</KnowledgeShell>;
}
