import Link from "next/link";
import { KnowledgeShell, dateLabel, label } from "@/components/knowledge-shell";
import { getTimeline } from "@/lib/api/server";

interface Filters { life_area?: string; event_type?: string; date_from?: string; date_to?: string }
export const metadata = { title: "Timeline" };
export default async function TimelinePage({ searchParams }: { searchParams: Promise<Filters> }) {
  const filters = await searchParams; const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value); });
  const data = await getTimeline(params).catch(() => ({ items: [], total: 0, limit: 50, offset: 0 }));
  return <KnowledgeShell eyebrow="Life model" title="Timeline" description="Chronological, source-grounded events. PDI does not generate narrative interpretations."><form className="mb-6 grid gap-2 rounded-xl bg-stone-100/70 p-3 sm:grid-cols-4"><select name="life_area" defaultValue={filters.life_area ?? ""} className="field"><option value="">All life areas</option>{["insurance","finance","vehicle","home","health","tax","work","travel","personal","other"].map((area) => <option key={area} value={area}>{label(area)}</option>)}</select><input name="event_type" defaultValue={filters.event_type ?? ""} className="field" placeholder="Event type" /><input name="date_from" type="date" defaultValue={filters.date_from ?? ""} className="field" /><button className="rounded-lg bg-stone-900 px-3 text-sm text-white">Apply filters</button></form>{data.items.length ? <ol className="divide-y divide-stone-200 border-y border-stone-200">{data.items.map((item) => <li key={item.id} className="grid gap-3 py-5 sm:grid-cols-[130px_1fr]"><time className="text-xs font-medium text-stone-400">{dateLabel(item.event_date)}</time><div><h2 className="text-sm font-medium text-stone-900">{item.title}</h2><p className="mt-1 text-xs text-stone-400">{label(item.life_area)} · {label(item.event_type)} · {label(item.event_date_precision)}</p>{item.evidence[0] ? <blockquote className="mt-3 border-l-2 border-amber-200 pl-3 text-sm text-stone-600">“{item.evidence[0].text}” <span className="text-xs text-stone-400">Page {item.evidence[0].page}</span></blockquote> : null}<Link href={`/documents/${item.source_document_id}`} className="mt-2 inline-block text-xs text-stone-500 hover:text-stone-950">Open source document →</Link></div></li>)}</ol> : <p className="py-16 text-center text-sm text-stone-400">No accepted events match these filters.</p>}</KnowledgeShell>;
}
