# syntax=docker/dockerfile:1.7
ARG DOCKER_CLI_IMAGE=docker:28-cli@sha256:625d9431a9f54c5a2bc90f24f0e1c3d55b1349fd857dd85035f98c2c9acbdd4d
ARG BACKEND_IMAGE

FROM ${DOCKER_CLI_IMAGE} AS docker_cli

ARG BACKEND_IMAGE
FROM ${BACKEND_IMAGE}

USER root
COPY --from=docker_cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker_cli /usr/local/libexec/docker/cli-plugins/docker-compose \
    /usr/local/libexec/docker/cli-plugins/docker-compose
USER pdi

ENTRYPOINT ["pdi"]
